export const ListActionTypes = {
  ACTIVATE_LIST: 'ACTIVATE_LIST',
  DELETE_LIST: 'DELETE_LIST',
  HANDLE_SUBMIT: 'HANDLE_SUBMIT',
  LIST_CREATE_ERROR: 'LIST_CREATE_ERROR',
  LIST_NAME_CHANGE: 'LIST_NAME_CHANGE',
  TOGGLE_CREATE_LIST_POPUP: 'TOGGLE_CREATE_LIST_POPUP',
};
