export const ListComponentActionTypes = {
  TASK_NAME_CHANGE: 'TASK_NAME_CHANGE',
  TASK_DETAILS_CHANGE: 'TASK_DETAILS_CHANGE',
  HANDLE_TASK_SUBMIT: 'HANDLE_TASK_SUBMIT',
  TASK_CREATE_ERROR: 'TASK_CREATE_ERROR',
  TOGGLE_TASK_FORM: 'TOGGLE_TASK_FORM',
  DELETE_TASK: 'DELETE_TASK',
  RESET_ACTIVE_TASKS: 'RESET_ACTIVE_TASKS',
  UPDATE_ACTIVE_TASKS: 'UPDATE_ACTIVE_TASKS',
};

export const ListContainerActionTypes = {
  ACTIVATE_LIST: 'ACTIVATE_LIST',
  CREATE_LIST_FAIL: 'CREATE_LIST_FAIL',
  CREATE_LIST_SUCCESS: 'CREATE_LIST_SUCCESS',
  DELETE_LIST_FAIL: 'DELETE_LIST_FAIL',
  DELETE_LIST_SUCCESS: 'DELETE_LIST_SUCCESS',
  FETCH_LISTS_FAIL: 'FETCH_LISTS_FAIL',
  FETCH_LISTS_SUCCESS: 'FETCH_LISTS_SUCCESS',
  HANDLE_SUBMIT: 'HANDLE_SUBMIT',
  LIST_CREATE_ERROR: 'LIST_CREATE_ERROR',
  LIST_NAME_CHANGE: 'LIST_NAME_CHANGE',
  RESET_ACTIVE_LIST: 'RESET_ACTIVE_LIST',
  TOGGLE_CREATE_LIST_POPUP: 'TOGGLE_CREATE_LIST_POPUP',
};

export const LoginActionTypes = {
  SEND_LOGIN_INFO: 'SEND_LOGIN_INFO',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
};
